[package]
name = "pixelflut_monoio"
version = "0.1.0"
edition = "2021"

[dependencies]
monoio = "0.2.4"

winit = "0.29.10"
softbuffer = "0.4.6"

toml = "0.8.19"
serde = { version = "1.0.210", features = ["derive"] }
bit-set = "0.8.0"
arrayvec = "0.7.6"
# bit-set = "0.5.3"
